### ISSUE TITLE
Loxone Adapter does not start after upgrading js-controller to 7.1.0

### ISSUE THREAD

**Issue by bergteam** [UncleSamSwiss/ioBroker.loxone#730]
**Describe the bug**  
Latest js-controller version 7.1.0 breaks the loxone adapter.

**To Reproduce**  
1. Iobroker with Loxone Adapter is working fine.
2. Upgrade js-controller from 7.0.7 to 7.1.0
  => Now Loxone Adapter does not Start anymore
3. Downgrade js-controller from 7.1.0 to 7.0.7
  => All is working again

**Screenshots & Logfiles**  
iobroker Web log on Loxone Adapter startup
```
2025-12-08 17:25:07.241	info	Restart adapter system.adapter.loxone.0 because enabled
2025-12-08 17:25:07.241	error	instance system.adapter.loxone.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2025-12-08 17:25:07.240	error	Caught by controller[1]: at Loxone.onReady (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:187:9)
2025-12-08 17:25:07.240	error	Caught by controller[1]: at Loxone.connect (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:245:27)
2025-12-08 17:25:07.240	error	Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-12-08 17:25:07.240	error	Caught by controller[1]: at Loxone.loadStructureFile (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:207:20)
2025-12-08 17:25:07.240	error	Caught by controller[1]: TypeError: sentry.addGlobalEventProcessor is not a function
2025-12-08 17:25:07.240	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

```

Log from File Log
```
2025-12-08 17:25:05.016  - info: host.iobroker instance system.adapter.loxone.0 in version "3.0.1" started with pid 180077
2025-12-08 17:25:06.295  - info: loxone.0 (180077) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.loxone, node: v22.21.0, js-controller: 7.1.0
2025-12-08 17:25:06.457  - info: loxone.0 (180077) Trying to connect
2025-12-08 17:25:06.670  - info: loxone.0 (180077) got structure file; last modified on 2025-12-08 10:44:05
2025-12-08 17:25:06.671  - error: loxone.0 (180077) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2025-12-08 17:25:06.671  - error: loxone.0 (180077) unhandled promise rejection: sentry.addGlobalEventProcessor is not a function
2025-12-08 17:25:06.689  - error: loxone.0 (180077) TypeError: sentry.addGlobalEventProcessor is not a function
    at Loxone.loadStructureFile (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:207:20)
    at Loxone.connect (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:245:27)
    at Loxone.onReady (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:187:9)
2025-12-08 17:25:06.690  - error: loxone.0 (180077) sentry.addGlobalEventProcessor is not a function
2025-12-08 17:25:06.701  - info: loxone.0 (180077) Socket closed 2003
2025-12-08 17:25:06.701  - info: loxone.0 (180077) terminating
2025-12-08 17:25:06.702  - warn: loxone.0 (180077) Terminated (UNCAUGHT_EXCEPTION): Without reason
2025-12-08 17:25:07.201  - info: loxone.0 (180077) terminating
2025-12-08 17:25:07.202  - info: loxone.0 (180077) terminating
2025-12-08 17:25:07.240  - error: host.iobroker Caught by controller[1]:     at Loxone.loadStructureFile (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:207:20)
2025-12-08 17:25:07.240  - error: host.iobroker Caught by controller[1]:     at Loxone.connect (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:245:27)
2025-12-08 17:25:07.240  - error: host.iobroker Caught by controller[1]:     at Loxone.onReady (/opt/iobroker/node_modules/iobroker.loxone/src/main.ts:187:9)
2025-12-08 17:25:07.241  - error: host.iobroker instance system.adapter.loxone.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2025-12-08 17:25:07.241  - info: host.iobroker Restart adapter system.adapter.loxone.0 because enabled
2025-
```

**Versions:**
//all latest on beta repo
-   Adapter version: loxone 3.0.1
-   JS-Controller version: 7.1.0
-   Node version: v22.21.0
-   Operating system: Debian trixie Container on Proxmox

**Comment by raintonr** [comment]
https://docs.sentry.io/platforms/javascript/guides/solid/migration/v7-to-v8/v7-deprecations/#deprecate-addglobaleventprocessor-in-favor-of-addeventprocessor
